impl From<PublicKey> for Address {}
termhn/nano-rs pull request #9
Opened 2018-04-19 20:02 UTC by SeunLanLege

2018-04-19 20:16 UTC, termhn commented
Awesome, thanks for this! I have a couple nits and will want to run some tests on the encoding before merging but looks great overall.

Nits (also commented in specific places...)

* Can you reformat to use 4 spaces per tab as this is standard Rust style and used throughout the rest of the project

2018-04-19 20:22 UTC, fu5ha requested changes
Nice job and thanks!! I was going to do this in a very similar way :D

2018-04-19 20:22 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +		let mut h = [0u8, 4].to_vec();
I believe you should only have to 0-pad with one byte (you really only need 4 bits but since that's harder to do this should work)

2018-04-19 20:22 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +			addr.push_str(encoded_addr.get(4..).unwrap());
This would change to `.get(1..)` I believe

2018-04-19 20:22 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +/// the address checksum is the 5byte hash of the public key reversed
Really it's just encoded in big endian byte order I believe...

2018-04-19 20:22 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +	buf.reverse();
With that in mind, we want to figure out an architecture-agnostic way of doing this here, though I haven't thought about what exactly the best way to do this is.

2018-04-19 20:22 UTC, fu5ha commented on nano-lib-rs/src/lib.rs
> +#[macro_use] extern crate data_encoding_macro;
Can you split this into two lines like
```rust
#[macro_use]
extern crate data_encoding_macro;
```
to be consistent with how it is throughout the rest of the code base? :D

2018-04-20 12:46 UTC, SeunLanLege commented on nano-lib-rs/src/keys.rs
> +	buf.reverse();
can you point out how it isn't architecture-agnostic? I can't tell.

2018-04-20 12:49 UTC, SeunLanLege commented on nano-lib-rs/src/keys.rs
> +/// the address checksum is the 5byte hash of the public key reversed
really? i was following https://flufd.github.io/nano/2018/03/22/generating-nano-addresses.html#encoding-the-public-key-in-the-nano-address-format

2018-04-20 12:51 UTC, SeunLanLege commented
As for tests, i think it would be much easier if i also added the impls for `From<Seed> for SecretKey`, `From<Address> for PublicKey` that way we can test end-to-end

2018-04-21 09:39 UTC, SeunLanLege commented
I've added the tests and the impls, and everything just works™ 

:confetti_ball:

2018-04-23 17:10 UTC, fu5ha requested changes
Sorry for the delay, this looks good... just a couple changes and if you could change from 8 spaces/tab to 4 spaces/tab again that'd be great! :)

2018-04-23 17:10 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +pub struct Seed(pub String);
I think really we want this to be `Seed(pub [u8; 64])`

2018-04-23 17:10 UTC, fu5ha commented on nano-lib-rs/src/keys.rs
> +	buf.reverse();
Hm... thinking about it more, I do think this is architecture agnostic.

2018-04-23 17:10 UTC, termhn commented on nano-lib-rs/src/keys.rs
> +		let seed_bytes = HEXUPPER_PERMISSIVE.decode(seed.0.as_bytes()).unwrap();
If we have seed as bytes we don't need to decode every time we want to use it

2018-04-24 06:48 UTC, SeunLanLege commented
I'm using 4spaces/1 tab

2018-04-24 06:50 UTC, fu5ha approved these changes

2018-04-24 06:50 UTC, merged

2018-04-24 06:50 UTC, termhn commented
LGTM! Thanks! :D